name: test plain lists

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenJDK 22
        run: |
          wget https://download.java.net/java/GA/jdk22/830ec9fcccef480bb3e73fb7ecafe059/36/GPL/openjdk-22_linux-x64_bin.tar.gz
          tar -xzvf openjdk-22_linux-x64_bin.tar.gz
      - name: run tests
        run: |
          ./jdk-22/bin/java --enable-preview --source 22 test-scripts/PlainListTests.java